### PR TITLE
Fix zombie process issues

### PR DESCRIPTION
**Pull request by rowanmanning**
Fixes the issue outlined in #45. @mfairchild365, could you verify this?

### CODE REVIEW

**Comment by mfairchild365** [comment]
@rowanmanning I ran the new code against a URL which was spawning zombies and it appears to fix the problem!  THANK YOU!  How can I send you a pizza?

**Comment by rowanmanning** [comment]
Haha no need :) just glad it's fixed! It's been toppling over our demo server as well.

**Comment by dotcode** [comment]
Hi @mfairchild365! As Rowan's manager, I'd just like to override his spurning of your kind offer of a pizza.

He'd love one really! Domino's is doing a 2-for-1 offer atm, and I know Rowan is partial to a slice of American Hot inside him.

https://www.dominos.co.uk

Rowan's postcode is N1 9SL, that'll be enough address information to get the pizzas to him.

Thanks!

**Comment by whymarrh** [comment]
Nice work @rowanmanning! :pizza:

**Pull request merged**
