### PR TITLE
Get and truncate the html source of messages from html_codesniffer

### PR DESCRIPTION
**Pull request by atambo**
This is basically a rebase of #56 against master plus adding some basic truncation.

### CODE REVIEW

**Comment by atambo** [comment]
@rowanmanning, @mfairchild365: Here is the rebase & truncation.

**Comment by Pikaling** [comment]
Glad to see you're working on this. I find pa11y difficult to use at the moment because I don't know where the element is that's causing the error.

**Comment by rowanmanning** [comment]
Hi @atambo, thanks for this. I've merged into the `develop` branch and made a small change I'd like to run by you before tagging for release: https://github.com/nature/pa11y/commit/413141d40cd993d33600d3dce17b0872092e6bce

**Comment by atambo** [comment]
@rowanmanning, good catch. Now the max length of html is 251 which sounds like a sane amount to me.

**Pull request merged**
